name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9.16', '3.10.9', '3.11.1']
    steps:
      - name: Checkout the repository at the current branch
        uses: actions/checkout@v3
      - name: Set up Python 3.11.1
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip build
      - name: Run build
        run: python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.6
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
